# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  sml_config = debug
  SMLTest_config = debug

else ifeq ($(config),release)
  sml_config = release
  SMLTest_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := sml SMLTest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

sml:
ifneq (,$(sml_config))
	@echo "==== Building sml ($(sml_config)) ===="
	@${MAKE} --no-print-directory -C . -f sml.make config=$(sml_config)
endif

SMLTest: sml
ifneq (,$(SMLTest_config))
	@echo "==== Building SMLTest ($(SMLTest_config)) ===="
	@${MAKE} --no-print-directory -C . -f SMLTest.make config=$(SMLTest_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f sml.make clean
	@${MAKE} --no-print-directory -C . -f SMLTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   sml"
	@echo "   SMLTest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"