name: LinuxRel32

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: premake
      run: sudo bash run_premake.sh
    - name: make
      run: make config=release_static32
      
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: unittest
        run: ./bin/Release-linux-/SMLTest/SMLTest
